<a href="https://colab.research.google.com/github/boampongj4125/Pandas-Project/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries

In [8]:
!pip install summarytools

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 23.0 MB/s eta 0:00:00


In [9]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from summarytools import dfSummary
import warnings
warnings.filterwarnings('ignore')

Importing the dataset

In [31]:
df = pd.read_csv('train.csv')

In [32]:
# Check column data types and missing values
dfSummary(df)

Removing columns

In [33]:
df = df.drop(df.columns[[2,7,8,9,10]], axis=1)
df

PassengerId  Pclass     Sex   Age  SibSp  Parch  Survived
0              1       3    male  22.0      1      0         0
1              2       1  female  38.0      1      0         1
2              3       3  female  26.0      0      0         1
3              4       1  female  35.0      1      0         1
4              5       3    male  35.0      0      0         0
..           ...     ...     ...   ...    ...    ...       ...
886          887       2    male  27.0      0      0         0
887          888       1  female  19.0      0      0         1
888          889       3  female   NaN      1      2         0
889          890       1    male  26.0      0      0         1
890          891       3    male  32.0      0      0         0

[891 rows x 7 columns]

In [34]:
x = df.iloc[: , :-1].values
y = df.iloc[: , -1].values

In [35]:
print(x)

[[1 3 'male' 22.0 1 0]
 [2 1 'female' 38.0 1 0]
 [3 3 'female' 26.0 0 0]
 ...
 [889 3 'female' nan 1 2]
 [890 1 'male' 26.0 0 0]
 [891 3 'male' 32.0 0 0]]


In [36]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

Handling missing data

In [37]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy= 'mean')
imputer.fit(x[:, 4:5])
x[: , 4:5] = imputer.transform(x[:, 4:5])

Encoding categorical variables

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [2])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [39]:
print(x)

[[0.0 1.0 1 ... 22.0 1.0 0]
 [1.0 0.0 2 ... 38.0 1.0 0]
 [1.0 0.0 3 ... 26.0 0.0 0]
 ...
 [1.0 0.0 889 ... nan 1.0 2]
 [0.0 1.0 890 ... 26.0 0.0 0]
 [0.0 1.0 891 ... 32.0 0.0 0]]
